import { Metadata } from 'next';
import { FileText } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Terms of Service | LawBridge',
  description:
    'Read the terms and conditions for using LawBridge, our AI-powered legal information service.',
};

export default function TermsPage() {
  return (
    <div className="min-h-full bg-[#0a0a0f]">
      {/* Hero */}
      <section className="hero-dark grid-pattern py-16 relative overflow-hidden">
        <div className="orb orb-cyan w-[300px] h-[300px] -top-20 -left-20 opacity-30" />
        
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center relative z-10">
          <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-cyan-500/20 border border-cyan-500/30 text-cyan-400 mb-6">
            <FileText className="w-8 h-8" />
          </div>
          <h1 className="text-4xl md:text-5xl font-bold text-white mb-4">
            Terms of Service
          </h1>
          <p className="text-[#a0a0b8]">
            Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
          </p>
        </div>
      </section>

      {/* Content */}
      <section className="py-16 px-4 sm:px-6 lg:px-8">
        <div className="max-w-3xl mx-auto space-y-6">
          {/* Important Disclaimer */}
          <div className="bg-amber-500/10 border border-amber-500/30 rounded-2xl p-6">
            <h2 className="text-lg font-semibold text-amber-300 mb-3">Important Disclaimer - Not Legal Advice</h2>
            <ul className="space-y-2 text-amber-200/80">
              <li>• LawBridge is NOT a law firm and does NOT provide legal advice.</li>
              <li>• The information provided is for general educational purposes only.</li>
              <li>• Using this Service does NOT create an attorney-client relationship.</li>
              <li>• You should ALWAYS consult with a licensed attorney for specific legal matters.</li>
            </ul>
          </div>

          <TermsSection title="1. Acceptance of Terms">
            <p>
              By accessing or using LawBridge (&ldquo;the Service&rdquo;), you agree to be bound by these Terms
              of Service (&ldquo;Terms&rdquo;). If you do not agree to these Terms, please do not use the Service.
            </p>
          </TermsSection>

          <TermsSection title="2. Description of Service">
            <p>
              LawBridge is an AI-powered platform that provides general legal information for
              educational purposes. The Service uses artificial intelligence to search legal databases
              and generate plain-language explanations of legal concepts.
            </p>
          </TermsSection>

          <TermsSection title="3. User Responsibilities">
            <p className="mb-2">By using the Service, you agree to:</p>
            <ul className="list-disc list-inside space-y-1 text-[#a0a0b8]">
              <li>Use the Service only for lawful purposes</li>
              <li>Not rely solely on the Service for legal decisions</li>
              <li>Not submit false, misleading, or malicious content</li>
              <li>Not attempt to circumvent security measures</li>
              <li>Not use the Service to harm, harass, or defraud others</li>
            </ul>
          </TermsSection>

          <TermsSection title="4. Intellectual Property">
            <p>
              The Service, including its design, features, and content is owned by LawBridge and 
              protected by intellectual property laws. You may not copy, modify, distribute, or 
              create derivative works without our express permission.
            </p>
          </TermsSection>

          <TermsSection title="5. AI-Generated Content">
            <p>
              Responses provided by the Service are generated by artificial intelligence based on
              retrieved legal documents. While we strive for accuracy, AI systems can make errors,
              and the information should be independently verified.
            </p>
          </TermsSection>

          <TermsSection title="6. Limitation of Liability">
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, LAWBRIDGE SHALL NOT BE LIABLE FOR ANY INDIRECT, 
              INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE SERVICE.
            </p>
          </TermsSection>

          <TermsSection title="7. Disclaimer of Warranties">
            <p>
              THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; WITHOUT WARRANTIES OF ANY KIND,
              EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF
              MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
            </p>
          </TermsSection>

          <TermsSection title="8. Changes to Terms">
            <p>
              We may modify these Terms at any time. We will notify users of material changes by
              posting the updated Terms on this page. Your continued use of the Service constitutes 
              acceptance of the modified Terms.
            </p>
          </TermsSection>

          <TermsSection title="9. Contact Information">
            <p>
              For questions about these Terms, please contact us at:
              <br />
              <a href="mailto:legal@lawbridge.app" className="text-emerald-400 hover:text-emerald-300 transition-colors">
                legal@lawbridge.app
              </a>
            </p>
          </TermsSection>
        </div>
      </section>
    </div>
  );
}

function TermsSection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="glass-card-dark rounded-2xl p-6">
      <h2 className="text-lg font-semibold text-white mb-3">{title}</h2>
      <div className="text-[#a0a0b8] leading-relaxed">
        {children}
      </div>
    </div>
  );
}
